apiVersion: apps/v1
kind: Deployment
metadata:
  name: boskos-reaper
  labels:
    app: boskos-reaper
  namespace: test-pods
spec:
  selector:
    matchLabels:
      app: boskos-reaper
  replicas: 1  # one canonical source of resources
  template:
    metadata:
      labels:
        app: boskos-reaper
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: boskos-reaper
        image: gcr.io/k8s-staging-boskos/reaper:v20240416-59dbd6c
        args:
        - --boskos-url=http://boskos.test-pods.svc.cluster.local.
        - --resource-type=vsphere-project-cluster-api-provider,vsphere-project-cloud-provider,vsphere-project-image-builder
